[book]
authors = ["Generic Associated Types Members"]
language = "en"
multilingual = false
src = "."
title = "Generic Associated Types Initiative"

[output.html]
no-section-label=true
git-repository-url="https://github.com/rust-lang/generic-associated-types-initiative"

[output.html.fold]
enable = true
level = 0
